namespace FuzzyCompare.Text;

using System;

/// <summary>
/// Defines the different categories of tokens that can be generated by the tokenizer.
/// </summary>
[Flags]
public enum TokenCategory
{
    /// <summary>
    /// No category is assigned.
    /// </summary>
    None            = 0,
    /// <summary>
    /// The token represents an unknown or undefined category.
    /// </summary>
    Other           = 1 << 0,
    /// <summary>
    /// The token represents a line break.
    /// </summary>
    LineBreak       = 1 << 1,
    /// <summary>
    /// The token represents a white space character.
    /// </summary>
    WhiteSpace      = 1 << 2,
    /// <summary>
    /// The token represents a word or identifier.
    /// </summary>
    Word            = 1 << 3,
    /// <summary>
    /// The token represents a numeric value.
    /// </summary>
    Number          = 1 << 4,
    /// <summary>
    /// The token represents a numeric value in a format other than decimal.
    /// </summary>
    OtherNumber     = 1 << 5,
    /// <summary>
    /// The token represents a punctuation mark.
    /// </summary>
    PunctuationMark = 1 << 6,
    /// <summary>
    /// The token represents a symbol or operator.
    /// </summary>
    Symbol          = 1 << 7,
}